### ISSUE TITLE
Why Fortran 77?

### ISSUE THREAD

**Issue by Beliavsky** [brenopelegrin/intro-fiscomp#1]
May I ask why the course is on Fortran 77 when all currently maintained compilers, such as gfortran and Intel Fortran, support Fortran 2003 and later standards?

**Comment by brenopelegrin** [comment]
Unfortunately, the professor is extremely old-fashioned and demands the use of this archaic version. Other professors who teach on this course generally use Fortran 90, which is at least a little more recent.

There isn't actually any advantage on using Fortran 77 and I personaly hate using it.
